---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: healthz-reader-role
rules:
  -
    apiGroups:
      - ""
    resources: [""]
    verbs: ["get"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]

